# This is a basic workflow starting with actions

name: CI

# Controls when the workflow will run

on:

  #triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  #allow you to run this workflow manually from the actions tab
  workflow_dispatch:

#a workflow run is mande up for one or more jobs that can run sequentially or in parallel
jobs:
  #this workflow contais a single job called "buid"
  CI:
  #the type of runner that the job will run on
    runs-on: ubuntu-latest

    #steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup do NodeJs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.13.2

      - name: Instalação do Mocha e dos pacotes para teste
        run:
          cd src;
          npm install -g mocha;
          npm install

      - name: Execução do teste
        run: mocha src/test/convert.js

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          
  
      - name: Construção da imagem
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
        uses: docker/build-push-action@v6.10.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            angelomoura/aula-conversao-temperatura:latest

